# Generated by Django 2.0 on 2019-04-02 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseData', '0001_initial'),
        ('ancillaryData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=120, verbose_name='调拨单号')),
                ('number', models.FloatField(verbose_name='系统数量')),
                ('actual_num', models.FloatField(verbose_name='实际数量')),
                ('difference', models.FloatField(verbose_name='盈亏数量')),
                ('date', models.DateField(verbose_name='盘点日期')),
                ('remarks', models.CharField(blank=True, default='', max_length=120, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '盘点',
                'verbose_name_plural': '盘点',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='品种')),
                ('dyelot_num', models.CharField(max_length=120, verbose_name='缸号')),
                ('batch_num', models.CharField(max_length=120, verbose_name='批号')),
                ('woolens_type', models.CharField(default='', max_length=120, verbose_name='毛料类型')),
                ('number', models.FloatField(null=True, verbose_name='数量')),
                ('assess_price', models.FloatField(null=True, verbose_name='评估单价')),
                ('actual_price', models.FloatField(null=True, verbose_name='实际单价')),
                ('create_people', models.CharField(blank=True, max_length=120, null=True, verbose_name='制单人')),
                ('create_date', models.DateField(default=datetime.datetime.now, verbose_name='制单时间')),
                ('check_status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('check_people', models.CharField(max_length=120, null=True, verbose_name='审核人')),
                ('check_date', models.DateField(default=datetime.datetime.now, verbose_name='审核时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Color', verbose_name='颜色')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Packaging', verbose_name='包装')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='baseData.Warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存表',
                'verbose_name_plural': '库存表',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=120, verbose_name='调拨单号')),
                ('transfers_num', models.FloatField(verbose_name='调拨数量')),
                ('date', models.DateField(verbose_name='调拨日期')),
                ('remarks', models.CharField(blank=True, default='', max_length=120, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='baseData.Warehouse', verbose_name='调出仓库')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.Inventory', verbose_name='库存')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='baseData.Warehouse', verbose_name='调入仓库')),
            ],
            options={
                'verbose_name': '调拨单',
                'verbose_name_plural': '调拨单',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.Inventory', verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='check',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Warehouse', verbose_name='仓库'),
        ),
    ]
