# Generated by Django 2.0 on 2019-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='woolens_type',
            field=models.CharField(choices=[('原材料', '原材料'), ('摇纱产品', '摇纱产品'), ('拼纱产品', '拼纱产品'), ('染色产品', '染色产品'), ('打毛产品', '打毛产品')], default='原材料', max_length=120, verbose_name='毛料类型'),
        ),
    ]
