# Generated by Django 2.0 on 2019-04-02 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_management', '0001_initial'),
        ('baseData', '0001_initial'),
        ('ancillaryData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=120, verbose_name='单号')),
                ('remain', models.FloatField(default=0, verbose_name='剩余数量')),
                ('number', models.FloatField(verbose_name='数量')),
                ('piece', models.FloatField(verbose_name='件数')),
                ('prick_num', models.FloatField(verbose_name='扎数')),
                ('price', models.FloatField(verbose_name='摇纱产品单价')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('ord_date', models.DateField(verbose_name='领料日期')),
                ('opposite_num', models.CharField(max_length=120, verbose_name='对方单号')),
                ('return_date', models.DateField(verbose_name='预计回毛日期')),
                ('remarks', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('complete_return', models.BooleanField(default=False, verbose_name='是否回毛完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Client', verbose_name='染色厂')),
                ('reeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.Inventory', verbose_name='摇纱产品')),
            ],
            options={
                'verbose_name': '染色领料',
                'verbose_name_plural': '染色领料',
            },
        ),
        migrations.CreateModel(
            name='DyeNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=120, verbose_name='单号')),
                ('name', models.CharField(max_length=120, verbose_name='品种')),
                ('dyelot_num', models.CharField(blank=True, max_length=120, verbose_name='缸号')),
                ('batch_num', models.CharField(blank=True, max_length=120, verbose_name='批号')),
                ('number', models.FloatField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('piece', models.FloatField(verbose_name='件数')),
                ('prick_num', models.FloatField(verbose_name='扎数')),
                ('ord_date', models.DateField(verbose_name='通知日期')),
                ('return_date', models.DateField(verbose_name='预计回毛日期')),
                ('complete_return', models.BooleanField(default=False, verbose_name='是否回毛完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Color', verbose_name='颜色')),
                ('dye', models.ManyToManyField(related_name='dye_notice', to='dye.Dye', verbose_name='所属染色领料')),
                ('dye_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dye_color', to='ancillaryData.Color', verbose_name='染色种类')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Packaging', verbose_name='包装')),
            ],
            options={
                'verbose_name': '染色通知',
                'verbose_name_plural': '染色通知',
            },
        ),
        migrations.CreateModel(
            name='DyeReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=120, verbose_name='单号')),
                ('name', models.CharField(max_length=120, verbose_name='品种')),
                ('dyelot_num', models.CharField(blank=True, max_length=120, verbose_name='缸号')),
                ('batch_num', models.CharField(max_length=120, verbose_name='批号')),
                ('number', models.FloatField(verbose_name='数量')),
                ('piece', models.FloatField(verbose_name='件数')),
                ('price', models.FloatField(verbose_name='摇纱产品单价')),
                ('total', models.FloatField(default=0, verbose_name='摇纱产品总额')),
                ('assess_price', models.FloatField(blank=True, verbose_name='评估单价')),
                ('actual_price', models.FloatField(blank=True, null=True, verbose_name='实际单价')),
                ('A', models.FloatField(blank=True, default=0.98, verbose_name='评估染色回毛率')),
                ('A1', models.FloatField(blank=True, default=0.0, verbose_name='实际染色回毛率')),
                ('process_price', models.FloatField(verbose_name='加工价')),
                ('process_total', models.FloatField(verbose_name='加工金额')),
                ('total_price', models.FloatField(verbose_name='总额')),
                ('return_date', models.DateField(verbose_name='回毛日期')),
                ('opposite_num', models.CharField(max_length=120, verbose_name='对方单号')),
                ('remarks', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('complete_return', models.BooleanField(default=False, verbose_name='是否回毛完成')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Color', verbose_name='颜色')),
                ('dye_notice', models.ManyToManyField(related_name='dye_return', to='dye.DyeNotice', verbose_name='所属染色通知单')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Packaging', verbose_name='包装')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Warehouse', verbose_name='回毛仓库')),
            ],
            options={
                'verbose_name': '染色回毛',
                'verbose_name_plural': '染色回毛',
            },
        ),
    ]
