# Generated by Django 2.0 on 2019-04-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseData', '0002_auto_20190402_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单号')),
                ('source_ordNum', models.CharField(max_length=60, verbose_name='源单号')),
                ('business_type', models.CharField(choices=[('购货订单', '购货订单'), ('购货单', '购货单'), ('摇纱领料单', '摇纱领料单'), ('拼纱领料单', '拼纱领料单'), ('染色领料单', '染色领料单'), ('打毛领料单', '打毛领料单')], max_length=60, verbose_name='业务类别')),
                ('date', models.DateField(verbose_name='单据日期')),
                ('money', models.FloatField(verbose_name='单据金额')),
                ('had_cancel', models.FloatField(verbose_name='已核销')),
                ('not_cancel', models.FloatField(verbose_name='未核销')),
                ('cancel', models.FloatField(verbose_name='本次核销')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due', to='baseData.Client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '应付款',
                'verbose_name_plural': '应付款',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单号')),
                ('payer', models.CharField(max_length=60, verbose_name='付款人')),
                ('date', models.DateField(verbose_name='单据日期')),
                ('account', models.CharField(max_length=60, verbose_name='结算账户')),
                ('pay_money', models.FloatField(verbose_name='付款金额')),
                ('pay_type', models.CharField(max_length=20, verbose_name='结算方式')),
                ('settlement_num', models.CharField(max_length=30, verbose_name='结算号')),
                ('remarks', models.CharField(max_length=120, verbose_name='备注')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='baseData.Client', verbose_name='客户')),
                ('due', models.ManyToManyField(to='money_management.Due', verbose_name='对应应付款单')),
            ],
            options={
                'verbose_name': '付款单',
                'verbose_name_plural': '付款单',
            },
        ),
    ]
