# Generated by Django 2.0 on 2019-04-03 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='payment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='due',
            name='cancel',
            field=models.FloatField(default=0, verbose_name='本次核销'),
        ),
        migrations.AlterField(
            model_name='due',
            name='date',
            field=models.DateField(null=True, verbose_name='单据日期'),
        ),
        migrations.AlterField(
            model_name='due',
            name='had_cancel',
            field=models.FloatField(default=0, verbose_name='已核销'),
        ),
        migrations.AlterField(
            model_name='due',
            name='money',
            field=models.FloatField(default=0, verbose_name='单据金额'),
        ),
        migrations.AlterField(
            model_name='due',
            name='not_cancel',
            field=models.FloatField(default=0, verbose_name='未核销'),
        ),
    ]
