# Generated by Django 2.0 on 2019-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0003_auto_20190403_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='business_type',
            field=models.CharField(choices=[('订货', '订货'), ('购货', '购货'), ('摇纱', '摇纱'), ('拼纱', '拼纱'), ('染色', '染色'), ('打毛', '打毛')], max_length=60, verbose_name='业务类别'),
        ),
    ]
