# Generated by Django 2.0 on 2019-04-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaryData', '0003_auto_20190410_1018'),
        ('money_management', '0004_auto_20190403_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Settlement', verbose_name='结算方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Account', verbose_name='结算账户'),
        ),
    ]
