# Generated by Django 2.0 on 2019-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0005_auto_20190410_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='due',
            name='cancel',
        ),
        migrations.AlterField(
            model_name='payment',
            name='ord_num',
            field=models.CharField(max_length=60, verbose_name='单据编号'),
        ),
    ]
