# Generated by Django 2.0 on 2019-04-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0006_auto_20190410_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='due',
        ),
        migrations.AddField(
            model_name='payment',
            name='due',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='money_management.Due', verbose_name='对应应付款单'),
            preserve_default=False,
        ),
    ]
