# Generated by Django 2.0 on 2019-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0007_auto_20190411_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
    ]
