# Generated by Django 2.0 on 2019-04-19 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaryData', '0003_auto_20190410_1018'),
        ('baseData', '0004_auto_20190419_2121'),
        ('money_management', '0009_auto_20190412_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, null=True, verbose_name='单号')),
                ('source_ordNum', models.CharField(max_length=60, verbose_name='源单号')),
                ('business_type', models.CharField(choices=[('订货', '订货'), ('购货', '购货'), ('摇纱', '摇纱'), ('拼纱', '拼纱'), ('染色', '染色'), ('打毛', '打毛')], max_length=60, verbose_name='业务类别')),
                ('date', models.DateField(null=True, verbose_name='单据日期')),
                ('money', models.FloatField(default=0, verbose_name='单据金额')),
                ('had_cancel', models.FloatField(default=0, verbose_name='已核销')),
                ('not_cancel', models.FloatField(default=0, verbose_name='未核销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_due', to='baseData.Client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '应收款',
                'verbose_name_plural': '应收款',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单据编号')),
                ('staff', models.CharField(max_length=60, verbose_name='收银人')),
                ('date', models.DateField(verbose_name='单据日期')),
                ('receipt_money', models.FloatField(verbose_name='收款金额')),
                ('settlement_num', models.CharField(max_length=30, verbose_name='结算号')),
                ('remarks', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Account', verbose_name='结算账户')),
            ],
            options={
                'verbose_name': '付款单',
                'verbose_name_plural': '付款单',
            },
        ),
        migrations.CreateModel(
            name='Receipt_to_AccountDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.FloatField(default=0, verbose_name='本次核销')),
                ('account_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_management.Account_Due', verbose_name='应收款')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_management.Receipt', verbose_name='收款单')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='account_due',
            field=models.ManyToManyField(through='money_management.Receipt_to_AccountDue', to='money_management.Account_Due', verbose_name='对应应收款单'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='baseData.Client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='settlement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillaryData.Settlement', verbose_name='结算方式'),
        ),
    ]
