# Generated by Django 2.0 on 2019-04-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0011_auto_20190423_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_due',
            options={'verbose_name': '应收款', 'verbose_name_plural': '应收款'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': '收款单', 'verbose_name_plural': '收款单'},
        ),
    ]
