# Generated by Django 2.0 on 2019-04-11 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_management', '0002_auto_20190402_1558'),
        ('baseData', '0003_auto_20190411_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单号')),
                ('staff', models.CharField(max_length=60, verbose_name='负责员工')),
                ('ord_date', models.DateField(verbose_name='出库时间')),
                ('take_num', models.FloatField(verbose_name='取货数量')),
                ('take_price', models.FloatField(verbose_name='取货单价')),
                ('take_total', models.FloatField(verbose_name='取货总价')),
            ],
            options={
                'verbose_name': '销售出货单',
                'verbose_name_plural': '销售出货单',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单号')),
                ('staff', models.CharField(max_length=60, verbose_name='销售人员')),
                ('sale_num', models.FloatField(verbose_name='销售数量')),
                ('sale_price', models.FloatField(verbose_name='销售单价')),
                ('sale_total', models.FloatField(verbose_name='销售总价')),
                ('book_num', models.FloatField(verbose_name='预订数量')),
                ('book_price', models.FloatField(verbose_name='预订单价')),
                ('book_total', models.FloatField(verbose_name='预订总价')),
                ('tax_price', models.FloatField(verbose_name='含税单价')),
                ('tax_total', models.FloatField(verbose_name='含税总价')),
                ('count', models.FloatField(verbose_name='价税合计')),
                ('ord_date', models.DateField(verbose_name='单据日期')),
                ('take_date', models.DateField(verbose_name='交货日期')),
                ('proceeds', models.FloatField(verbose_name='本次收款')),
                ('arrear', models.FloatField(verbose_name='本次欠款')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Account', verbose_name='结算账户')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Client', verbose_name='客户')),
                ('woolens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.Inventory', verbose_name='毛料')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_num', models.CharField(max_length=60, verbose_name='单号')),
                ('staff', models.CharField(max_length=60, verbose_name='销售人员')),
                ('sale_num', models.FloatField(verbose_name='销售数量')),
                ('sale_price', models.FloatField(verbose_name='销售单价')),
                ('sale_total', models.FloatField(verbose_name='销售总价')),
                ('book_num', models.FloatField(verbose_name='预订数量')),
                ('book_price', models.FloatField(verbose_name='预订单价')),
                ('book_total', models.FloatField(verbose_name='预订总价')),
                ('tax_price', models.FloatField(verbose_name='含税单价')),
                ('tax_total', models.FloatField(verbose_name='含税总价')),
                ('count', models.FloatField(verbose_name='价税合计')),
                ('remain', models.FloatField(verbose_name='剩余数量')),
                ('ord_date', models.DateField(verbose_name='单据日期')),
                ('take_date', models.DateField(verbose_name='交货日期')),
                ('deadline', models.DateField(verbose_name='最晚取货日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseData.Client', verbose_name='客户')),
                ('woolens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.Inventory', verbose_name='毛料')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
            },
        ),
        migrations.AddField(
            model_name='saleexport',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SalesOrder', verbose_name='所属销售订单'),
        ),
    ]
