# Generated by Django 2.0 on 2019-04-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseData', '0003_auto_20190411_2137'),
        ('warehouse_management', '0002_auto_20190402_1558'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.RenameModel(
            old_name='SalesOrder',
            new_name='SaleOrder',
        ),
        migrations.RenameField(
            model_name='saleexport',
            old_name='sales_order',
            new_name='sale_order',
        ),
    ]
