# Generated by Django 2.0 on 2019-04-11 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20190411_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleexport',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
