# Generated by Django 2.0 on 2019-04-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_saleexport_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='saleexport',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
    ]
