# Generated by Django 2.0 on 2019-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190411_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleexport',
            name='sale_order',
        ),
        migrations.AddField(
            model_name='saleexport',
            name='sale_order',
            field=models.ManyToManyField(related_name='sale_export', to='sale.SaleOrder', verbose_name='所属销售订单'),
        ),
    ]
