# Generated by Django 2.0 on 2019-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20190412_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='proceeds',
            field=models.FloatField(default=0, verbose_name='本次收款'),
            preserve_default=False,
        ),
    ]
