# Generated by Django 2.0 on 2019-04-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseData', '0002_auto_20190402_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
    ]
