# Generated by Django 2.0 on 2019-05-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseData', '0004_auto_20190419_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('username',)},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name',)},
        ),
    ]
