# Generated by Django 2.0 on 2019-05-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseData', '0005_auto_20190509_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_client', to='baseData.Client', verbose_name='所属客户'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'client')},
        ),
    ]
