# Generated by Django 2.0 on 2019-04-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_times',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='登录次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(default=1, max_length=120, verbose_name='工号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='operate',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='电话'),
        ),
    ]
