# Generated by Django 2.0 on 2019-04-10 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaryData', '0002_auto_20190402_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='结算方式')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '结算方式',
                'verbose_name_plural': '结算方式',
            },
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('name',)},
        ),
    ]
