# Generated by Django 2.0 on 2019-05-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaryData', '0003_auto_20190410_1018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('color', 'color_num')},
        ),
    ]
